<x-card-text class="card-text">
  <x-slot name="aside">
    <h2>{{ __('Verantwortlich für den Inhalt') }}
  </x-slot>
  <x-slot name="content">
    {!! __('<p>Visualisierungs-Akademie Schweiz GmbH<br>Oliver Schmid<br>Limmatstrasse 291<br>8005 Zürich<br>Schweiz</p>') !!}
    {!! __('<p><a href="mailto:oliver.schmid@visualisierungs-akademie.ch" target="_blank" title="E-Mail oliver.schmid@visualisierungs-akademie.ch">oliver.schmid@visualisierungs-akademie.ch</a><br>Telefon: <a href="tel:+41435014040" title="Telefon +41 43 501 40 40">+41 43 501 40 40</a></p>') !!}
    {!! __('<p>MWST-Nr. CHE-110.279.761 MWST<br>Handelsreg.-Nr. CH-020.4.027.770-0</p>') !!}
  </x-slot>
</x-card-text>

<x-card-text class="card-text">
  <x-slot name="aside">
    <h2>{{ __('Copyright') }}
  </x-slot>
  <x-slot name="content">
    <p>{{ __('Das Copyright für sämtliche Inhalte dieser Website liegt bei der Visualisierungs-Akademie Schweiz GmbH, Oliver Schmid.') }}</p>
  </x-slot>
</x-card-text>

<x-card-text class="card-text">
  <x-slot name="aside">
    <h2>{{ __('Umsetzung') }}
  </x-slot>
  <x-slot name="content">
    <p>{!! __('Design und Branding:<br>WBG AG, Zürich, <a href="https://www.wbg.ch" target="_blank" title="WBG AG, Zürich">www.wbg.ch</a>') !!}</p>
    <p>{!! __('Programmierung:<br>Marcel Stadelmann, Zürich, <a href="https://www.marceli.to" target="_blank" title="Marcel Stadelmann, marceli.to">www.marceli.to</a>') !!}</p>
    <p>{!! __('Portraits:<br>Simon Hallström, <a href="https://www.simonhallstroem.com" target="_blank" title="Simon Hallström">www.simonhallstroem.com</a><br>Christoph Deiters, <a href="https://www.nightnurse.ch" target="_blank" title="Christoph Deiters">www.nightnurse.ch</a><br>Oliver Schmid, <a href="https://www.visualisierungs-akademie.ch" target="_blank" title="Oliver Schmid">www.visualisierungs-akademie.ch</a>') !!}</p>
  </x-slot>
</x-card-text>

<x-card-text class="card-text">
  <x-slot name="aside">
    <h2>{{ __('Disclaimer') }}
  </x-slot>
  <x-slot name="content">
    <p>{{ __('Alle Texte und Links wurden sorgfältig geprüft und werden laufend aktualisiert. Wir sind bemüht, richtige und vollständige Informationen auf dieser Website bereitzustellen, übernehmen aber keinerlei Verantwortung, Garantien oder Haftung dafür, dass die durch diese Website bereitgestellten Informationen, richtig, vollständig oder aktuell sind. Wir behalten uns das Recht vor, jederzeit und ohne Vorankündigung die Informationen auf dieser Website zu ändern und verpflichten uns auch nicht, die enthaltenen Informationen zu aktualisieren. Alle Links zu externen Anbietern wurden zum Zeitpunkt ihrer Aufnahme auf ihre Richtigkeit überprüft, dennoch haften wir nicht für Inhalte und Verfügbarkeit von Websites, die mittels Hyperlinks zu erreichen sind. Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die durch Inhalte verknüpfter Seiten entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde. Dabei ist es gleichgültig, ob der Schaden direkter, indirekter oder finanzieller Natur ist oder ein sonstiger Schaden vorliegt, der sich aus Datenverlust, Nutzungsausfall oder anderen Gründen aller Art ergeben könnte.') }}</p>
  </x-slot>
</x-card-text>

<x-card-text class="card-text privacy">
  <x-slot name="aside">
    <h2>{{ __('Datenschutzerklärung') }}
  </x-slot>
  <x-slot name="content">
    <p>Mit dieser <strong>Datenschutzerklärung</strong> informieren wir, welche Personendaten wir im Zusammenhang mit unseren <strong>Aktivitäten und Tätigkeiten</strong> einschliesslich unserer <strong><nobr>https://visualisierungs-akademie.ch/</nobr>-Website</strong> bearbeiten. Wir informieren insbesondere, wofür, wie und wo wir Personendaten bearbeiten. Wir informieren ausserdem über die Rechte von Personen, deren Daten wir bearbeiten.</p>
    <p>Für einzelne oder zusätzliche Aktivitäten und Tätigkeiten können weitere Datenschutzerklärungen sowie sonstige rechtliche Dokumente wie Allgemeine Geschäftsbedingungen (AGB), Nutzungsbedingungen oder Teilnahmebedingungen gelten.</p>
    <p>Wir unterliegen dem schweizerischen Datenschutzrecht sowie allenfalls anwendbarem ausländischem Datenschutzrecht wie insbesondere jenem der Europäischen Union (EU) mit der Datenschutz-Grundverordnung (DSGVO). Die Europäische Kommission <a href="https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX%3A32000D0518" rel="nofollow noopener noreferrer" target="_blank">anerkennt</a>, dass das schweizerische Datenschutzrecht einen angemessenen Datenschutz gewährleistet.</p>
    <h2>1. Kontaktadressen</h2>
    <p>Verantwortung für die Bearbeitung von Personendaten:</p>
    <p><strong>Oliver Schmid</strong><br />
    Visualisierungs-Akademie Schweiz GmbH<br />
    Limmatstrasse 291<br />
    8005 Zürich</p>
    <p><a href="mailto:oliver.schmid@visualisierungs-akademie.ch">oliver.schmid@visualisierungs-akademie.ch</a></p>
    <p>Wir weisen darauf hin, wenn es im Einzelfall andere Verantwortliche für die Bearbeitung von Personendaten gibt.</p>
    <h3>1.1 Datenschutzbeauftragter</h3>
    <p>Wir verfügen über nachfolgenden Datenschutzbeauftragten als Anlaufstelle für betroffene Personen und als Ansprechpartner für Aufsichtsbehörden bei datenschutzrechtlichen Anfragen:</p>
    <p><strong>Oliver Schmid</strong><br />
    Visualisierungs-Akademie Schweiz GmbH<br />
    Limmatstrasse 291<br />
    8005 Zürich</p>
    <p><a href="mailto:oliver.schmid@visualisierungs-akademie.ch">oliver.schmid@visualisierungs-akademie.ch</a></p>
    <h3>1.2 Datenschutz-Vertretung im Europäischen Wirtschaftsraum (EWR)</h3>
    <p>Wir verfügen über nachfolgende Datenschutz-Vertretung gemäss <a href="https://steigerlegal.ch/dsgvo/dsgvo-27/" rel="nofollow noopener noreferrer" target="_blank">Art. 27 DSGVO</a>. Die Datenschutz-Vertretung dient Aufsichtsbehörden und betroffenen Personen in der Europäischen Union (EU) und im übrigen Europäischen Wirtschaftsraum (EWR) als <em>zusätzliche</em> Anlaufstelle für Anfragen im Zusammenhang mit der Datenschutz-Grundverordnung (DSGVO):</p>
    <p><a href="https://www.datenschutzpartner.eu/kontakt/" rel="nofollow noopener noreferrer" target="_blank"><strong>VGS Datenschutzpartner GmbH</strong></a><br />
    Am Kaiserkai 69<br />
    20457 Hamburg<br />
    Deutschland</p>
    <p><a href="mailto:info@datenschutzpartner.eu">info@datenschutzpartner.eu</a></p>
    <h2>2. Begriffe und Rechtsgrundlagen</h2>
    <h3>2.1 Begriffe</h3>
    <p><strong>Personendaten</strong> sind <em>alle</em> Angaben, die sich auf eine bestimmte oder bestimmbare Person beziehen. Eine <strong>betroffene Person</strong> ist eine Person, über die Personendaten bearbeitet werden.</p>
    <p><strong>Bearbeiten</strong> umfasst <em>jeden</em> Umgang mit Personendaten, <em>unabhängig</em> von den angewandten Mitteln und Verfahren, insbesondere das Aufbewahren, Bekanntgeben, Beschaffen, Erheben, Löschen, Speichern, Verändern, Vernichten und Verwenden von Personendaten.</p>
    <p>Der <strong>Europäische Wirtschaftsraum (EWR)</strong> umfasst die Mitgliedstaaten der Europäischen Union (EU) sowie das Fürstentum Liechtenstein, Island und Norwegen. Die Datenschutz-Grundverordnung (DSGVO) bezeichnet die Bearbeitung von Personendaten als Verarbeitung von personenbezogenen Daten.</p>
    <h3>2.2 Rechtsgrundlagen</h3>
    <p>Wir bearbeiten Personendaten im Einklang mit dem schweizerischen Datenschutzrecht wie insbesondere dem <a href="https://www.fedlex.admin.ch/eli/cc/1993/1945_1945_1945/de" rel="nofollow noopener noreferrer" target="_blank">Bundesgesetz über den Datenschutz</a> (DSG) und der <a href="https://www.fedlex.admin.ch/eli/cc/1993/1962_1962_1962/de" rel="nofollow noopener" target="_blank">Verordnung zum Bundesgesetz über den Datenschutz</a> (VDSG).</p>
    <p><span>Wir bearbeiten – sofern und soweit die Datenschutz-Grundverordnung (DSGVO) anwendbar ist – Personendaten gemäss <em>mindestens</em> einer der folgenden Rechtsgrundlagen:</span></p>
    <ul>
    <li><a href="https://steigerlegal.ch/dsgvo/dsgvo-6/" rel="nofollow noopener noreferrer" target="_blank">Art. 6 Abs. 1 lit. b DSGVO</a> für die erforderliche Bearbeitung von Personendaten zur Erfüllung eines Vertrages mit der betroffenen Person sowie zur Durchführung vorvertraglicher Massnahmen.</li>
    <li>Art. 6 Abs. 1 lit. f DSGVO für die erforderliche Bearbeitung von Personendaten, um die berechtigten Interessen von uns oder von Dritten zu wahren, sofern nicht die Grundfreiheiten und Grundrechte sowie Interessen der betroffenen Person überwiegen. Berechtigte Interessen sind insbesondere unser Interesse, unsere Aktivitäten und Tätigkeiten dauerhaft, nutzerfreundlich, sicher und zuverlässig ausüben sowie darüber kommunizieren zu können, die Gewährleistung der Informationssicherheit, der Schutz vor Missbrauch, die Durchsetzung von eigenen rechtlichen Ansprüchen und die Einhaltung von schweizerischem Recht.</li>
    <li>Art. 6 Abs. 1 lit. c DSGVO für die erforderliche Bearbeitung von Personendaten zur Erfüllung einer rechtlichen Verpflichtung, der wir gemäss allenfalls anwendbarem Recht von Mitgliedstaaten im Europäischen Wirtschaftsraum (EWR) unterliegen.</li>
    <li>Art. 6 Abs. 1 lit. e DSGVO für die erforderliche Bearbeitung von Personendaten zur Wahrnehmung einer Aufgabe, die im öffentlichen Interesse liegt.</li>
    <li>Art. 6 Abs. 1 lit. a DSGVO für die Bearbeitung von Personendaten mit Einwilligung der betroffenen Person.</li>
    <li>Art. 6 Abs. 1 lit. d DSGVO für die erforderliche Bearbeitung von Personendaten, um lebenswichtige Interessen der betroffenen Person oder einer anderen natürlichen Person zu schützen.</li>
    </ul>
    <h2>3. Art, Umfang und Zweck</h2>
    <p>Wir bearbeiten jene Personendaten, die <em>erforderlich</em> sind, um unsere Aktivitäten und Tätigkeiten dauerhaft, nutzerfreundlich, sicher und zuverlässig ausüben zu können. Solche Personendaten können insbesondere in die Kategorien von Bestandes- und Kontaktdaten, Browser- und Gerätedaten, Inhaltsdaten, Meta- bzw. Randdaten und Nutzungsdaten, Standortdaten, Verkaufsdaten sowie Vertrags- und Zahlungsdaten fallen.</p>
    <p>Wir bearbeiten Personendaten während jener <em>Dauer</em>, die für den jeweiligen Zweck bzw. die jeweiligen Zwecke oder gesetzlich erforderlich ist. Personendaten, deren Bearbeitung nicht mehr erforderlich ist, werden anonymisiert oder gelöscht.</p>
    <p>Wir können Personendaten <em>durch Dritte</em> bearbeiten lassen. Wir können Personendaten gemeinsam mit Dritten bearbeiten oder an Dritte übermitteln. Bei solchen Dritten handelt es sich insbesondere um spezialisierte Anbieter, deren Leistungen wir in Anspruch nehmen. Wir gewährleisten auch bei solchen Dritten den Datenschutz.</p>
    <p>Wir bearbeiten Personendaten nur nach Einwilligung der betroffenen Person, es sei denn, die Bearbeitung ist aus anderen rechtlichen Gründen zulässig. Die Bearbeitung ohne Einwilligung kann beispielsweise zulässig sein zur Erfüllung eines Vertrages mit der betroffenen Person und für entsprechende vorvertragliche Massnahmen, um unsere überwiegenden berechtigten Interessen zu wahren, weil die Bearbeitung aus den Umständen ersichtlich ist oder nach vorgängiger Information.</p>
    <p>In diesem Rahmen bearbeiten wir insbesondere Angaben, die eine betroffene Person bei der Kontaktaufnahme&nbsp;– beispielsweise per Briefpost, E-Mail, Instant Messaging, Kontaktformular, Social Media oder Telefon&nbsp;– oder bei der Registrierung für ein Nutzerkonto <em>freiwillig</em> an uns übermittelt. Wir können solche Angaben beispielsweise in einem Adressbuch, in einem Customer Relationship Management-System (CRM-System) oder mit vergleichbaren Hilfsmitteln speichern. Wenn wir Daten über andere Personen übermittelt erhalten, sind die übermittelnden Personen verpflichtet, den Datenschutz gegenüber diesen Personen zu gewährleisten sowie die Richtigkeit dieser Personendaten sicherzustellen.</p>
    <p>Wir bearbeiten ausserdem Personendaten, die wir von Dritten erhalten, aus öffentlich zugänglichen Quellen beschaffen oder bei der Ausübung unserer Aktivitäten und Tätigkeiten erheben, sofern und soweit eine solche Bearbeitung aus rechtlichen Gründen zulässig ist.</p>
    <h2>4. Bewerbungen</h2>
    <p>Wir bearbeiten Personendaten über Bewerberinnen und Bewerber, soweit sie für die Einschätzung der Eignung für ein Arbeitsverhältnis oder für die spätere Durchführung eines Arbeitsvertrages erforderlich sind. Die erforderlichen Personendaten ergeben sich insbesondere aus den abgefragten Angaben, beispielsweise im Rahmen einer Stellenausschreibung. Wir bearbeiten ferner jene Personendaten, die Bewerberinnen und Bewerber <em>freiwillig</em> mitteilen oder veröffentlichen, insbesondere als Teil von Anschreiben, Lebenslauf und sonstigen Bewerbungsunterlagen sowie von Online-Profilen.</p>
    <p><span>Wir bearbeiten&nbsp;– sofern und soweit die Datenschutz-Grundverordnung (DSGVO) anwendbar ist&nbsp;– Personendaten über Bewerberinnen und Bewerber insbesondere gemäss <a href="https://steigerlegal.ch/dsgvo/dsgvo-9/#2b" rel="nofollow noopener noreferrer" target="_blank">Art.&nbsp;9 Abs.&nbsp;2 lit.&nbsp;b DSGVO</a>.</p>
    <h2>5. Personendaten im Ausland</h2>
    <p>Wir bearbeiten Personendaten <em>grundsätzlich</em> in der Schweiz und im Europäischen Wirtschaftsraum (EWR). Wir können Personendaten aber auch in andere Staaten exportieren bzw. übermitteln, insbesondere um sie dort zu bearbeiten oder bearbeiten zu lassen.</p>
    <p>Wir können Personendaten in alle <a href="https://de.wikipedia.org/wiki/Liste_der_Staaten_der_Erde#Tabelle" rel="nofollow noopener noreferrer" target="_blank">Staaten und Territorien auf der Erde</a> sowie anderswo im <a href="https://de.wikipedia.org/wiki/Universum" rel="nofollow noopener noreferrer" target="_blank">Universum</a> exportieren, sofern das dortige Recht nach <a href="https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/handel-und-wirtschaft/uebermittlung-ins-ausland.html" rel="nofollow noopener noreferrer" target="_blank">Einschätzung des Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten</a> (EDÖB) oder gemäss <a href="https://steigerlegal.ch/2022/09/10/ndsg-schweiz-staatenliste/" rel="nofollow noopener noreferrer" target="_blank">Beschluss des Schweizerischen Bundesrates</a> einen angemessenen Datenschutz sowie – sofern und soweit die Datenschutz-Grundverordnung (DSGVO) anwendbar ist – gemäss <a href="https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/adequacy-decisions_de" rel="nofollow noopener noreferrer" target="_blank">Beschluss der Europäischen Kommission</a> einen angemessenen Datenschutz gewährleistet. </p>
    <p>Wir können Personendaten in Staaten, deren Recht keinen angemessenen Datenschutz gewährleistet, übermitteln, sofern der Datenschutz aus anderen Gründen gewährleistet ist, insbesondere auf Grundlage von Standarddatenschutzklauseln oder mit anderen geeigneten Garantien. Ausnahmsweise können wir Personendaten in Staaten ohne angemessenen oder geeigneten Datenschutz exportieren, wenn dafür die besonderen datenschutzrechtlichen Voraussetzungen erfüllt sind, beispielsweise die ausdrückliche Einwilligung der betroffenen Personen oder ein unmittelbarer Zusammenhang mit dem Abschluss oder der Abwicklung eines Vertrages. Wir geben betroffenen Personen auf Nachfrage gerne Auskunft über allfällige Garantien oder liefern eine Kopie von Garantien.</p>
    <h2>6. Rechte von betroffenen Personen</h2>
    <p>Betroffene Personen, über die wir Personendaten bearbeiten, verfügen über die Rechte gemäss schweizerischem Datenschutzrecht. Dazu zählen das Recht auf Auskunft sowie das Recht auf Berichtigung, Löschung oder Sperrung der bearbeiteten Personendaten.</p>
    <p>Betroffene Personen, deren Personendaten wir bearbeiten, können&nbsp;– sofern und soweit die Datenschutz-Grundverordnung (DSGVO) anwendbar ist&nbsp;– unentgeltlich eine Bestätigung verlangen, ob wir sie betreffende Personendaten bearbeiten. In diesem Fall können betroffene Personen Auskunft über die Bearbeitung ihrer Personendaten verlangen, die Bearbeitung ihrer Personendaten einschränken lassen, ihr Recht auf Datenübertragbarkeit wahrnehmen sowie ihre Personendaten berichtigen, löschen («Recht auf Vergessen»), sperren oder vervollständigen lassen.</p>
    <p>Betroffene Personen, deren Personendaten wir bearbeiten, können&nbsp;– sofern und soweit die DSGVO anwendbar ist&nbsp;– eine erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen und jederzeit Widerspruch gegen die Bearbeitung ihrer Personendaten erheben.</p>
    <p>Betroffene Personen, über die wir Personendaten bearbeiten, verfügen über ein Beschwerderecht bei einer zuständigen Aufsichtsbehörde. Aufsichtsbehörde für den Datenschutz in der Schweiz ist der <a href="https://www.edoeb.admin.ch/edoeb/de/home/der-edoeb/kontakt.html" rel="nofollow noopener noreferrer" target="_blank">Eidgenössische Datenschutz- und Öffentlichkeitsbeauftragte</a> (EDÖB).</p>
    <h2>7. Datensicherheit</h2>
    <p>Wir treffen geeignete technische und organisatorische Massnahmen, um eine dem jeweiligen Risiko angemessene Datensicherheit zu gewährleisten. Wir können aber keine absolute Datensicherheit gewährleisten.</p>
    <p>Der Zugriff auf unsere Website erfolgt mittels Transportverschlüsselung (SSL&nbsp;/ TLS, insbesondere mit dem Hypertext Transfer Protocol Secure, abgekürzt HTTPS). Die meisten Browser kennzeichnen Transportverschlüsselung mit einem Vorhängeschloss in der Adressleiste.</p>
    <p>Unsere digitale Kommunikation unterliegt&nbsp;– wie <em>grundsätzlich</em> jede digitale Kommunikation&nbsp;– der Massenüberwachung ohne Anlass und Verdacht sowie sonstiger Überwachung durch Sicherheitsbehörden in der Schweiz, im übrigen Europa, in den Vereinigten Staaten von Amerika (USA) und in anderen Staaten. Wir können keinen direkten Einfluss auf die entsprechende Bearbeitung von Personendaten durch Geheimdienste, Polizeistellen und andere Sicherheitsbehörden nehmen.</p>
    <h2>8. Nutzung der Website</h2>
    <h3>8.1 Cookies</h3>
    <p>Wir können Cookies verwenden. Bei Cookies&nbsp;– eigenen Cookies (First-Party-Cookies) als auch Cookies von Dritten, deren Dienste wir nutzen (Third-Party-Cookies)&nbsp;– handelt es sich um Daten, die im Browser gespeichert werden. Solche gespeicherten Daten müssen nicht auf traditionelle Cookies in Textform beschränkt sein.</p>
    <p>Cookies können im Browser temporär als «Session Cookies» oder für einen bestimmten Zeitraum als sogenannte permanente Cookies gespeichert werden. «Session Cookies» werden automatisch gelöscht, wenn der Browser geschlossen wird. Permanente Cookies haben eine bestimmte Speicherdauer. Cookies ermöglichen insbesondere, einen Browser beim nächsten Besuch unserer Website wiederzuerkennen und dadurch beispielsweise die Reichweite unserer Website zu messen. Permanente Cookies können aber beispielsweise auch für Online-Marketing verwendet werden.</p>
    <p>Cookies können in den Browser-Einstellungen jederzeit ganz oder teilweise deaktiviert sowie gelöscht werden. Ohne Cookies steht unsere Website allenfalls nicht mehr in vollem Umfang zur Verfügung. Wir ersuchen&nbsp;– mindestens sofern und soweit erforderlich&nbsp;– aktiv um die ausdrückliche Einwilligung in die Verwendung von Cookies.</p>
    <p>Bei Cookies, die für die Erfolgs- und Reichweitenmessung oder für Werbung verwendet werden, ist für zahlreiche Dienste ein allgemeiner Widerspruch («Opt-out») über die <a href="https://youradchoices.ca/" rel="nofollow noopener noreferrer" target="_blank">AdChoices</a> (Digital Advertising Alliance of Canada), die <a href="https://optout.networkadvertising.org/" rel="nofollow noopener noreferrer" target="_blank">Network Advertising Initiative</a> (NAI), <a href="https://optout.aboutads.info/" rel="nofollow noopener noreferrer" target="_blank">YourAdChoices</a> (Digital Advertising Alliance) oder <a href="https://www.youronlinechoices.com/ch-de/praferenzmanagement" rel="nofollow noopener noreferrer" target="_blank">Your Online Choices</a> (European Interactive Digital Advertising Alliance, EDAA) möglich.</p>
    <h3>8.2 Server-Logdateien</h3>
    <p>Wir können für jeden Zugriff auf unsere Website nachfolgende Angaben erfassen, sofern diese von Ihrem Browser an unsere Server-Infrastruktur übermittelt werden oder von unserem Webserver ermittelt werden können: Datum und Zeit einschliesslich Zeitzone, Internet Protocol (IP)-Adresse, Zugriffsstatus (HTTP-Statuscode), Betriebssystem einschliesslich Benutzeroberfläche und Version, Browser einschliesslich Sprache und Version, aufgerufene einzelne Unter-Seite unserer Website einschliesslich übertragener Datenmenge, zuletzt im gleichen Browser-Fenster aufgerufene Webseite (Referer bzw. Referrer).</p>
    <p>Wir speichern solche Angaben, die auch Personendaten darstellen können, in Server-Logdateien. Die Angaben sind erforderlich, um unsere Website dauerhaft, nutzerfreundlich und zuverlässig bereitstellen sowie um die Datensicherheit und damit insbesondere den Schutz von Personendaten sicherstellen zu können – auch durch Dritte oder mit Hilfe von Dritten.</p>
    <h3>8.3 Zählpixel</h3>
    <p>Wir können Zählpixel auf unserer Website verwenden. Zählpixel werden auch als Web-Beacons bezeichnet. Bei Zählpixeln&nbsp;– auch von Dritten, deren Dienste wir nutzen&nbsp;– handelt es sich um kleine, üblicherweise nicht sichtbare Bilder, die beim Besuch unserer Website automatisch abgerufen werden. Mit Zählpixeln können die gleichen Angaben wie in Server-Logdateien erfasst werden.</p>
    <h2>9. Benachrichtigungen und Mitteilungen</h2>
    <p>Wir versenden Benachrichtigungen und Mitteilungen per E-Mail und über andere Kommunikationskanäle wie beispielsweise Instant Messaging oder SMS.</p>
    <h3>9.1 Erfolgs- und Reichweitenmessung</h3>
    <p>Benachrichtigungen und Mitteilungen können Weblinks oder Zählpixel enthalten, die erfassen, ob eine einzelne Mitteilung geöffnet wurde und welche Weblinks dabei angeklickt wurden. Solche Weblinks und Zählpixel können die Nutzung von Benachrichtigungen und Mitteilungen auch personenbezogen erfassen. Wir benötigen diese statistische Erfassung der Nutzung für die Erfolgs- und Reichweitenmessung, um Benachrichtigungen und Mitteilungen aufgrund der Bedürfnisse und Lesegewohnheiten der Empfängerinnen und Empfänger effektiv und nutzerfreundlich sowie dauerhaft, sicher und zuverlässig versenden zu können.</p>
    <h3>9.2 Einwilligung und Widerspruch</h3>
    <p>Sie müssen <em>grundsätzlich</em> in die Verwendung Ihrer E-Mail-Adresse und Ihrer sonstigen Kontaktadressen ausdrücklich einwilligen, es sei denn, die Verwendung ist aus anderen rechtlichen Gründen zulässig. Für eine allfällige Einwilligung verwenden wir nach Möglichkeit das «Double Opt-in»-Verfahren, das heisst, Sie erhalten eine E-Mail mit einem Weblink, den Sie zur Bestätigung anklicken müssen, damit kein Missbrauch durch unberechtigte Dritte erfolgen kann. Wir können solche Einwilligungen einschliesslich Internet Protocol (IP)-Adresse sowie Datum und Zeit aus Beweis- und Sicherheitsgründen protokollieren.</p>
    <p>Sie können <em>grundsätzlich</em> dem Erhalt von Benachrichtigungen und Mitteilungen wie beispielsweise Newslettern jederzeit widersprechen. Mit einem solchen Widerspruch können Sie gleichzeitig der statistischen Erfassung der Nutzung für die Erfolgs- und Reichweitenmessung widersprechen. Vorbehalten bleiben erforderliche Benachrichtigungen und Mitteilungen im Zusammenhang mit unseren Aktivitäten und Tätigkeiten.</p>
    <h3>9.3 Dienstleister für Benachrichtigungen und Mitteilungen</h3>
    <p>Wir versenden Benachrichtigungen und Mitteilungen mit Hilfe von spezialisierten Dienstleistern.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://mailchimp.com/de/" rel="nofollow noopener noreferrer" target="_blank">Mailchimp:</a></strong> Kommunikationsplattform; Anbieterin: The Rocket Science Group&nbsp;LLC d/b/a Mailchimp (USA) als <a href="https://www.intuit.com/legal/intuit-group-companies/" rel="nofollow noopener noreferrer" target="_blank">Tochtergesellschaft</a> der Intuit&nbsp;Inc. (USA); Angaben zum Datenschutz: <a href="https://www.intuit.com/privacy/statement/" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Intuit)</a> einschliesslich «Länder- und Regionen-spezifische Bestimmungen» («Country and Region-Specific Terms»)</a>, <a href="https://mailchimp.com/help/mailchimp-intuit-privacy-faq/" rel="nofollow noopener noreferrer" target="_blank">«Häufig gestellte Fragen zum Datenschutz bei Mailchimp»</a>, <a href="https://mailchimp.com/de/help/mailchimp-european-data-transfers/" rel="nofollow noopener noreferrer" target="_blank">«Mailchimp und europäische Datenübertragungen»</a>, <a href="https://mailchimp.com/about/security/" rel="nofollow noopener noreferrer" target="_blank">«Sicherheit»</a>, <a href="https://mailchimp.com/legal/cookies/" rel="nofollow noopener noreferrer" target="_blank">Cookie-Richtlinie</a>, <a href="https://mailchimp.com/privacy-rights/" rel="nofollow noopener noreferrer" target="_blank">«Datenschutzrechtliche Anfragen» («Privacy Rights Requests»)</a>, <a href="https://mailchimp.com/legal/" rel="nofollow noopener noreferrer" target="_blank">«Rechtliche Bestimmungen»</a>.
    </li>
    <li><strong><a href="https://www.mailgun.com/de/" rel="nofollow noopener noreferrer" target="_blank">Mailgun:</a></strong> Plattform für Transaktions-E-Mails; Anbieterinnen: Mailgun Technologies&nbsp;Inc. (USA) gemeinsam mit Tochtergesellschaften («Mailgun Group»); Angaben zum Datenschutz: <a href="https://www.mailgun.com/privacy-policy/" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>.
    </li>
    </ul>
    <h2>10. Social Media</h2>
    <p>Wir sind auf Social Media-Plattformen und anderen Online-Plattformen präsent, um mit interessierten Personen kommunizieren sowie über unsere Aktivitäten und Tätigkeiten informieren zu können. Im Zusammenhang mit solchen Plattformen können Personendaten auch ausserhalb der Schweiz und des Europäischen Wirtschaftsraumes (EWR) bearbeitet werden.</p>
    <p>Es gelten jeweils auch die Allgemeinen Geschäftsbedingungen (AGB) und Nutzungsbedingungen sowie Datenschutzerklärungen und sonstigen Bestimmungen der einzelnen Betreiber solcher Plattformen. Diese Bestimmungen informieren insbesondere über die Rechte von betroffenen Personen direkt gegenüber der jeweiligen Plattform, wozu beispielsweise das Recht auf Auskunft zählt.</p>
    <p>Für unsere <strong>Social Media-Präsenz bei Facebook</strong> unter Einschluss der sogenannten Seiten-Insights sind wir&nbsp;– sofern und soweit die Datenschutz-Grundverordnung (DSGVO) anwendbar ist&nbsp;– gemeinsam mit der Meta Platforms Ireland Limited (Irland) verantwortlich. Die Meta Platforms Ireland Limited ist Teil der <a href="https://www.facebook.com/help/111814505650678" rel="nofollow noopener noreferrer" target="_blank">Meta-Unternehmen</a> (unter anderem in den USA). Die Seiten-Insights geben Aufschluss darüber, wie Besucherinnen und Besucher mit unserer Facebook-Präsenz interagieren. Wir verwenden Seiten-Insights, um unsere Social Media-Präsenz bei Facebook effektiv und nutzerfreundlich bereitstellen zu können.</p>
    <p>Weitere Angaben über Art, Umfang und Zweck der Datenbearbeitung, Angaben zu den Rechten von betroffenen Personen sowie die Kontaktdaten von Facebook wie auch dem Datenschutzbeauftragten von Facebook finden sich in der <a href="https://www.facebook.com/about/privacy" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung von Facebook</a>. Wir haben mit Facebook den sogenannten <a href="https://www.facebook.com/legal/controller_addendum" rel="nofollow noopener noreferrer" target="_blank">«Zusatz für Verantwortliche»</a> abgeschlossen und damit insbesondere vereinbart, dass Facebook dafür verantwortlich ist, die Rechte betroffener Personen zu gewährleisten. Für die sogenannten Seiten-Insights finden sich die entsprechenden Angaben auf der Seite <a href="https://www.facebook.com/legal/terms/page_controller_addendum" rel="nofollow noopener noreferrer" target="_blank">«Informationen zu Seiten-Insights»</a> einschliesslich <a href="https://www.facebook.com/legal/terms/information_about_page_insights_data" rel="nofollow noopener noreferrer" target="_blank">«Informationen zu Seiten-Insights-Daten»</a>.</p>
    <h2>11. Dienste von Dritten</h2>
    <p>Wir nutzen Dienste von spezialisierten Dritten, um unsere Aktivitäten und Tätigkeiten dauerhaft, nutzerfreundlich, sicher und zuverlässig ausüben zu können. Mit solchen Diensten können wir unter anderem Funktionen und Inhalte in unsere Website einbetten. Bei einer solchen Einbettung erfassen die genutzten Dienste aus technisch zwingenden Gründen mindestens zeitweilig die Internet Protocol&nbsp;(IP)-Adressen der Nutzerinnen und Nutzer.</p>
    <p>Für erforderliche sicherheitsrelevante, statistische und technische Zwecke können Dritte, deren Dienste wir nutzen, Daten im Zusammenhang mit unseren Aktivitäten und Tätigkeiten aggregiert, anonymisiert oder pseudonymisiert bearbeiten. Es handelt sich beispielsweise um Leistungs- oder Nutzungsdaten, um den jeweiligen Dienst anbieten zu können.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://about.google/products/" rel="nofollow noopener noreferrer" target="_blank">Dienste von Google:</a></strong> Anbieterinnen: Google&nbsp;LLC (USA) / Google Ireland Limited (Irland) für Nutzerinnen und Nutzer im Europäischen Wirtschaftsraum (EWR) und in der Schweiz; Allgemeine Angaben zum Datenschutz: <a href="https://safety.google/intl/de/principles/" rel="nofollow noopener noreferrer" target="_blank">«Grundsätze zu Datenschutz und Sicherheit»</a>, <a href="https://policies.google.com/privacy?hl=de" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://privacy.google.com/intl/de/businesses/compliance/" rel="nofollow noopener noreferrer" target="_blank">«Google ist der Einhaltung der anwendbaren Datenschutzgesetze verpflichtet»</a>, <a href="https://policies.google.com/technologies/product-privacy?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Leitfaden zum Datenschutz in Google-Produkten»</a>, <a href="https://policies.google.com/technologies/partner-sites?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Wie wir Daten von Websites oder Apps verwenden, auf bzw. in denen unsere Dienste genutzt werden» (Angaben von Google)</a>, <a href="https://policies.google.com/technologies/cookies?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Von Google verwendete Cookie-Arten und sonstige Technologien»</a>, <a href="https://adssettings.google.com/" rel="nofollow noopener noreferrer" target="_blank">«Personalisierte Werbung» (Aktivierung / Deaktivierung / Einstellungen)</a>.
    </li>
    <li><strong><a href="https://www.microsoft.com/de-ch" rel="nofollow noopener noreferrer" target="_blank">Dienste von Microsoft:</a></strong> Anbieterinnen: Microsoft Corporation (USA)&nbsp;/ Microsoft Ireland Operations Limited (Irland) für Nutzerinnen und Nutzer im Europäischen Wirtschaftsraum (EWR), in Grossbritannien und in der Schweiz; Allgemeine Angaben zum Datenschutz: <a href="https://privacy.microsoft.com/de-de" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz bei Microsoft»</a>, <a href="https://www.microsoft.com/de-ch/trust-center/privacy" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz (Trust Center)»</a>, <a href="https://privacy.microsoft.com/de-de/privacystatement" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>.
    </li>
    </ul>
    <h3>11.1 Digitale Infrastruktur</h3>
    <p>Wir nutzen Dienste von spezialisierten Dritten, um benötigte digitale Infrastruktur im Zusammenhang mit unseren Aktivitäten und Tätigkeiten in Anspruch nehmen zu können. Dazu zählen beispielsweise Hosting- und Speicherdienste von ausgewählten Anbietern.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://www.metanet.ch/de" rel="nofollow noopener noreferrer" target="_blank">METANET:</a></strong> Hosting; Anbieterin: METANET&nbsp;AG (Schweiz); Angaben zum Datenschutz: <a href="https://www.metanet.ch/de/ueber-metanet/datenschutzerklaerung" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://www.metanet.ch/media/57/download/Technisch_organisatorische_Massnahmen_v1_0_a.pdf" rel="nofollow noopener noreferrer" target="_blank">«Technisch-organisatorische Massnahmen»</a>.
    </li>
    </ul>
    <h3>11.2 Kontaktmöglichkeiten</h3>
    <p>Wir nutzen Dienste von ausgewählten Anbietern, um mit Dritten wie beispielsweise potenziellen sowie bestehenden Kundinnen und Kunden besser kommunizieren zu können.</p>
    <h3>11.3 Audio- und Video-Konferenzen</h3>
    <p>Wir nutzen spezialisierte Dienste für Audio- und Video-Konferenzen, um online kommunizieren zu können. Wir können damit beispielsweise virtuelle Besprechungen abhalten oder Online-Unterricht und Webinare durchführen. Für die Teilnahme an Audio- und Video-Konferenzen gelten ergänzend die Rechtstexte der einzelnen Dienste wie Datenschutzerklärungen und Nutzungsbedingungen.</p>
    <p>Wir empfehlen, je nach Lebenssituation bei der Teilnahme an Audio- oder Video-Konferenzen das Mikrofon standardmässig stumm zu schalten sowie den Hintergrund unscharf zu stellen oder einen virtuellen Hintergrund einblenden zu lassen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://meet.google.com" rel="nofollow noopener noreferrer" target="_blank">Google Meet:</a></strong> Video-Konferenzen; Anbieterin: Google; Google Meet-spezifische Angaben: <a href="https://support.google.com/meet/answer/9852160" rel="nofollow noopener noreferrer" target="_blank">«Google Meet&nbsp;– Sicherheit und Datenschutz für Nutzer»</a>.
    </li>
    <li><strong><a href="https://www.gotomeeting.com/de-ch" rel="nofollow noopener noreferrer" target="_blank">GoToMeeting:</a></strong> Video-Konferenzen; Anbieterinnen: LogMeIn USA für Nutzerinnen und Nutzer in den USA / LogMeIn Ireland Unlimited Company (Irland) für Nutzerinnen und Nutzer in sonstigen Staaten und Territorien auf der Erde sowie anderswo im Universum; Angaben zum Datenschutz: <a href="https://www.logmein.com/de/legal/privacy/international" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (international)</a>, <a href="https://www.logmein.com/de/legal/privacy/us" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (USA)</a>.
    </li>
    <li><strong><a href="https://www.microsoft.com/de-de/microsoft-teams/group-chat-software" rel="nofollow noopener noreferrer" target="_blank">Microsoft Teams:</a></strong> Plattform unter anderem für Audio- und Video-Konferenzen; Anbieterin: Microsoft; Teams-spezifische Angaben: <a href="https://docs.microsoft.com/de-de/microsoftteams/teams-privacy" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz und Microsoft Teams»</a>.
    </li>
    <li><strong><a href="https://www.skype.com/de/" rel="nofollow noopener noreferrer" target="_blank">Skype:</a></strong> Audio- und Video-Konferenzen; Skype-spezifische Anbieterinnen: Skype Communications&nbsp;SARL (Luxemburg)&nbsp;/ Microsoft Corporation (USA)&nbsp;/ Microsoft Ireland Operations Limited (Irland) für Nutzerinnen und Nutzer im Europäischen Wirtschaftsraum (EWR), in Grossbritannien und in der Schweiz; Angaben zum Datenschutz: <a href="https://www.skype.com/de/legal/" rel="nofollow noopener noreferrer" target="_blank">«Rechtliches zu Skype»</a>, <a href="https://support.skype.com/de/skype/all/privacy-security/" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz und Sicherheit»</a>.
    </li>
    <li><strong><a href="https://zoom.us/" rel="nofollow noopener noreferrer" target="_blank">Zoom:</a></strong> Video-Konferenzen; Anbieterin: Zoom Video Communications Inc. (USA); Angaben zum Datenschutz: <a href="https://zoom.us/de-de/privacy.html" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://zoom.us/de-de/trust/privacy.html" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz bei Zoom»</a>, <a href="https://zoom.us/de-de/trust/legal-compliance.html" rel="nofollow noopener noreferrer" target="_blank">«Rechtskonformitäts-Center»</a>.
    </li>
    </ul>
    <h3>11.4 Online-Zusammenarbeit</h3>
    <p>Wir nutzen Dienste von Dritten, um die Online-Zusammenarbeit zu ermöglichen. Es gelten ergänzend zu dieser Datenschutzerklärung jeweils auch allenfalls direkt ersichtliche Bedingungen der genutzten Dienste wie beispielsweise Nutzungsbedingungen oder Datenschutzerklärungen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://miro.com/de/" rel="nofollow noopener noreferrer" target="_blank">Miro:</a></strong> Whiteboard-Plattform; Anbieterin: RealtimeBoard Inc. (USA); Angaben zum Datenschutz: <a href="https://miro.com/legal/privacy-policy/" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://miro.com/security/" rel="nofollow noopener noreferrer" target="_blank">«Vertrauen in Miro» («Miro Trust Center»)</a>.
    </li>
    <li><strong><a href="https://www.notion.so/" rel="nofollow noopener noreferrer" target="_blank">Notion:</a></strong> Plattform für Team-Zusammenarbeit; Anbieterin: Notion Labs&nbsp;Inc. (USA); Angaben zum Datenschutz: <a href="https://www.notion.so/Privacy-Policy-3468d120cf614d4c9014c09f6adc9091" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://www.notion.so/security" rel="nofollow noopener noreferrer" target="_blank">«Sicherheit&nbsp;& Datenschutz» («Security&nbsp;& Privacy»)</a>, <a href="https://www.notion.so/Cookie-Notice-bc186044eed5488a8387a9e94b14e58c" rel="nofollow noopener noreferrer" target="_blank">Cookie-Richtlinie</a>.
    </li>
    </ul>
    <h3>11.5 Social Media-Funktionen und Social Media-Inhalte</h3>
    <p>Wir nutzen Dienste und Plugins von Dritten, um Funktionen und Inhalte von Social Media-Plattformen einbetten zu können sowie um das Teilen von Inhalten auf Social Media-Plattformen und auf anderen Wegen zu ermöglichen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://developers.facebook.com/products/social-plugins/" rel="nofollow noopener noreferrer" target="_blank">Facebook (Soziale Plugins):</a></strong> Einbetten von Facebook-Funktionen und Facebook-Inhalten, zum Beispiel «Gefällt mir» («Like») oder «Teilen» («Share»); Anbieterinnen: Meta Platforms Ireland Limited (Irland) und <a href="https://www.facebook.com/help/111814505650678" rel="nofollow noopener noreferrer" target="_blank">weitere Meta-Unternehmen</a> (unter anderem in den USA); Angaben zum Datenschutz: <a href="https://www.facebook.com/policy.php" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>.
    </li>
    <li><strong><a href="https://developers.facebook.com/docs/instagram" rel="nofollow noopener noreferrer" target="_blank">Instagram-Plattform:</a></strong> Einbetten von Instagram-Inhalten; Anbieterinnen: Meta Platforms Ireland Limited (Irland) und <a href="https://www.facebook.com/help/111814505650678" rel="nofollow noopener noreferrer" target="_blank">weitere Meta-Unternehmen</a> (unter anderem in den USA); Angaben zum Datenschutz: <a href="https://help.instagram.com/519522125107875" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Instagram)</a>, <a href="https://www.facebook.com/policy.php" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Facebook)</a>.
    </li>
    <li><strong><a href="https://docs.microsoft.com/linkedin/consumer/" rel="nofollow noopener noreferrer" target="_blank">LinkedIn Consumer Solutions Platform:</a></strong> Einbetten von Funktionen und Inhalten von LinkedIn, zum Beispiel mit <a href="https://developer.linkedin.com/product-catalog/plugins" rel="nofollow noopener noreferrer" target="_blank">Plugins</a> wie dem <a href="https://docs.microsoft.com/linkedin/consumer/integrations/self-serve/plugins/share-plugin" rel="nofollow noopener noreferrer" target="_blank">«Share Plugin»</a>; Anbieterin: Microsoft; LinkedIn-spezifische Angaben: <a href="https://privacy.linkedin.com" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz» («Privacy»)</a>, <a href="https://www.linkedin.com/legal/privacy-policy" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://www.linkedin.com/legal/cookie-policy" rel="nofollow noopener noreferrer" target="_blank">Cookie-Richtlinie</a>, <a href="https://www.linkedin.com/psettings/guest-controls" rel="nofollow noopener noreferrer" target="_blank">Cookie-Verwaltung&nbsp;/ Widerspruch gegen E-Mail und SMS-Kommunikation von LinkedIn</a>, <a href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out" rel="nofollow noopener noreferrer" target="_blank">Widerspruch gegen interessenbezogene Werbung</a>.
    </li>
    </ul>
    <h3>11.6 Kartenmaterial</h3>
    <p>Wir nutzen Dienste von Dritten, um Karten in unsere Website einbetten zu können.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://www.google.com/maps" rel="nofollow noopener noreferrer" target="_blank">Google Maps</a></strong> einschliesslich <strong><a href="https://cloud.google.com/maps-platform" rel="nofollow noopener noreferrer" target="_blank">Google Maps Platform:</a></strong> Kartendienst; Anbieterin: Google; Google Maps-spezifische Angaben: <a href="https://policies.google.com/technologies/location-data?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Wie Google Standortinformationen verwendet»</a>.
    </li>
    </ul>
    <h3>11.7 Digitale Audio- und Video-Inhalte</h3>
    <p>Wir nutzen Dienste von spezialisierten Dritten, um das direkte Abspielen von digitalen Audio- und Video-Inhalten wie beispielsweise Musik oder Podcasts zu ermöglichen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://vimeo.com/de/" rel="nofollow noopener noreferrer" target="_blank">Vimeo:</a></strong> Video-Plattform; Anbieterin: Vimeo&nbsp;Inc. (USA); Angaben zum Datenschutz: <a href="https://help.vimeo.com/hc/de/sections/203915088-Datenschutz" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz»</a>, <a href="https://vimeo.com/privacy" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>.
    </li>
    <li><strong><a href="https://www.youtube.com/" rel="nofollow noopener noreferrer" target="_blank">YouTube:</a></strong> Video-Plattform; Anbieterin: Google; YouTube-spezifische Angaben: <a href="https://support.google.com/youtube/topic/2803240?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz- und Sicherheitscenter»</a>, <a href="https://support.google.com/youtube/answer/9315727?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Meine Daten auf YouTube»</a>.
    </li>
    </ul>
    <h3>11.8 Schriftarten</h3>
    <p>Wir nutzen Dienste von Dritten, um ausgewählte Schriftarten sowie Icons, Logos und Symbole in unsere Website einbetten zu können.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://fonts.adobe.com/" rel="nofollow noopener noreferrer" target="_blank">Adobe Fonts:</a></strong> Schriftarten; Anbieterinnen: Adobe&nbsp;Inc. (USA) für Nutzerinnen und Nutzer in Nordamerika&nbsp;/ Adobe Systems Software Ireland Limited (Irland) für Nutzerinnen und Nutzer im Rest der Welt; Angaben zum Datenschutz: <a href="https://www.adobe.com/de/privacy.html" rel="nofollow noopener noreferrer" target="_blank">«Datenschutzzentrum von Adobe»</a>, <a href="https://www.adobe.com/ch_de/privacy/policies/adobe-fonts.html" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Adobe Fonts)</a>, <a href="https://www.adobe.com/ch_de/privacy/policy.html" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Adobe)</a>, <a href="https://www.adobe.com/ch_de/privacy/privacy-contact.html" rel="nofollow noopener noreferrer" target="_blank">«Fragen zum Datenschutz?»</a>, <a href="https://www.adobe.com/ch_de/privacy/opt-out.html" rel="nofollow noopener noreferrer" target="_blank">«Adobe-Datenschutzeinstellungen»</a>.
    </li>
    </ul>
    <h3>11.9 E-Commerce</h3>
    <p>Wir betreiben E-Commerce und nutzen Dienste von Dritten, um Dienstleistungen, Inhalte oder Waren erfolgreich anbieten zu können.</p>
    <h3>11.10 Zahlungen</h3>
    <p>Wir nutzen spezialisierte Dienstleister, um Zahlungen unserer Kundinnen und Kunden sicher und zuverlässig abwickeln zu können. Für die Abwicklung von Zahlungen gelten ergänzend die Rechtstexte der einzelnen Dienstleister wie Allgemeine Geschäftsbedingungen (AGB) oder Datenschutzerklärungen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://stripe.com/de-ch" rel="nofollow noopener noreferrer" target="_blank">Stripe:</a></strong> Abwicklung von Zahlungen; Anbieterinnen: Stripe Inc. (USA) / Stripe Payments Europe Limited (SPEL, Irland) für Nutzerinnen und Nutzer im Europäischen Wirtschaftsraum (EWR) und in der Schweiz sowie teilweise in Grossbritannien / Stripe Payments UK Limited (Grossbritannien) und Stripe Capital Europe Limited (Irland) teilweise für Nutzerinnen und Nutzer in Grossbritannien; Angaben zum Datenschutz: <a href="https://stripe.com/privacy-center/legal" rel="nofollow noopener noreferrer" target="_blank">«Stripe Datenschutz Center» («Stripe Privacy Center»)</a>, <a href="https://stripe.com/de-ch/privacy" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://stripe.com/cookies-policy/legal" rel="nofollow noopener noreferrer" target="_blank">Cookie-Richtlinie</a>.
    </li>
    </ul>
    <h3>11.11 Werbung</h3>
    <p>Wir nutzen die Möglichkeit, gezielt <strong>Werbung für unsere Aktivitäten und Tätigkeiten</strong> bei Dritten wie beispielsweise Social Media-Plattformen und Suchmaschinen anzeigen zu lassen.</p>
    <p>Wir möchten mit solcher Werbung insbesondere Personen erreichen, die sich für unsere Aktivitäten und Tätigkeiten bereits interessieren oder sich dafür interessieren könnten (<strong>Remarketing</strong> und <strong>Targeting</strong>). Dafür können wir entsprechende&nbsp;– allenfalls auch personenbezogene&nbsp;– Angaben an Dritte, die solche Werbung ermöglichen, übermitteln. Wir können ausserdem feststellen, ob unsere Werbung erfolgreich ist, das heisst insbesondere, ob sie zu Besuchen auf unserer Website führt <strong>(Conversion Tracking)</strong>.</p>
    <p>Dritte, bei denen wir werben und wo Sie als Nutzerin oder Nutzer angemeldet sind, können die Nutzung unseres Online-Angebotes allenfalls Ihrem dortigen Profil zuordnen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://www.facebook.com/business/ads" rel="nofollow noopener noreferrer" target="_blank">Facebook-Werbung (Facebook Ads):</a></strong> Social Media-Werbung; Anbieterinnen: Meta Platforms Ireland Limited (Irland) und <a href="https://www.facebook.com/help/111814505650678" rel="nofollow noopener noreferrer" target="_blank">weitere Meta-Unternehmen</a> (unter anderem in den USA); Angaben zum Datenschutz: Remarketing und Targeting insbesondere mit dem <strong>Facebook-Pixel</strong> sowie <strong>Custom Audiences</strong> einschliesslich <strong>Lookalike Audiences</strong>, <a href="https://www.facebook.com/policy.php" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://www.facebook.com/ads/preferences" rel="nofollow noopener noreferrer" target="_blank">«Werbepräferenzen»</a> (Anmeldung als Nutzerin oder Nutzer erforderlich).
    </li>
    <li><strong><a href="https://ads.google.com/intl/de_de/home/" rel="nofollow noopener noreferrer" target="_blank">Google Ads:</a></strong> Suchmaschinen-Werbung; Anbieterin: Google; Google Ads-spezifische Angaben: Werbung unter anderem aufgrund von Suchanfragen, wobei verschiedene Domainnamen – insbesondere doubleclick.net, googleadservices.com und googlesyndication.com – für Google Ads verwendet werden, <a href="https://policies.google.com/technologies/ads?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Werbung» (Google)</a>, <a href="https://support.google.com/ads/answer/1634057?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Warum sehe ich eine bestimmte Werbung?»</a>.
    </li>
    <li><strong><a href="https://business.instagram.com/advertising/" rel="nofollow noopener noreferrer" target="_blank">Instagram Ads:</a></strong> Social Media-Werbung; Anbieterinnen: Meta Platforms Ireland Limited (Irland) und <a href="https://www.facebook.com/help/111814505650678" rel="nofollow noopener noreferrer" target="_blank">weitere Meta-Unternehmen</a> (unter anderem in den USA); Angaben zum Datenschutz: Remarketing und Targeting insbesondere mit <strong>Facebook-Pixel</strong> sowie <strong>Custom Audiences</strong> einschliesslich <strong>Lookalike Audiences</strong>, <a href="https://help.instagram.com/519522125107875" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Instagram)</a>, <a href="https://www.facebook.com/policy.php" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung (Facebook)</a>, <a href="https://www.instagram.com/accounts/access_tool/ads_interests" rel="nofollow noopener noreferrer" target="_blank">«Werbepräferenzen» (Instagram)</a> (Anmeldung als Nutzerin oder Nutzer erforderlich), <a href="https://www.facebook.com/ads/preferences" rel="nofollow noopener noreferrer" target="_blank">«Werbepräferenzen» (Facebook)</a> (Anmeldung als Nutzerin oder Nutzer erforderlich).
    </li>
    <li><strong><a href="https://business.linkedin.com/marketing-solutions/ads" rel="nofollow noopener noreferrer" target="_blank">LinkedIn Ads:</a></strong> Social Media-Werbung; Anbieterinnen: LinkedIn Corporation (USA) / LinkedIn Ireland Unlimited Company (Irland); Angaben zum Datenschutz: Remarketing und Targeting insbesondere mit dem <strong>LinkedIn Insight Tag</strong>,  <a href="https://privacy.linkedin.com" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz»</a>, <a href="https://www.linkedin.com/legal/privacy-policy" rel="nofollow noopener noreferrer" target="_blank">Datenschutzerklärung</a>, <a href="https://www.linkedin.com/legal/cookie-policy" rel="nofollow noopener noreferrer" target="_blank">Cookie-Richtlinie</a>, <a href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out" rel="nofollow noopener noreferrer" target="_blank">Widerspruch gegen personalisierte Werbung</a>.
    </li>
    </ul>
    <h2>12. Erfolgs- und Reichweitenmessung</h2>
    <p>Wir nutzen Dienste und Programme, um zu ermitteln, wie unser Online-Angebot genutzt wird. In diesem Rahmen können wir beispielsweise den Erfolg und die Reichweite unserer Aktivitäten und Tätigkeiten sowie die Wirkung von Verlinkungen Dritter auf unsere Website messen. Wir können aber beispielsweise auch ausprobieren und vergleichen, wie unterschiedliche Versionen unseres Online-Angebotes oder Teile unseres Online-Angebotes genutzt werden («A/B-Test»-Methode). Aufgrund der Ergebnisse der Erfolgs- und Reichweitenmessung können wir insbesondere Fehler beheben, beliebte Inhalte stärken oder Verbesserungen an unserem Online-Angebot vornehmen.</p>
    <p>Bei der Verwendung von Diensten und Programmen für die Erfolgs- und Reichweitenmessung müssen die Internet Protocol&nbsp;(IP)-Adressen von einzelnen Nutzerinnen und Nutzern gespeichert werden. IP-Adressen werden <em>grundsätzlich</em> gekürzt («IP-Masking»), um durch die entsprechende Pseudonymisierung dem Grundsatz der Datensparsamkeit zu folgen und damit den Datenschutz der Nutzerinnen und Nutzer zu verbessern.</p>
    <p>Bei der Verwendung von Diensten und Programmen für die Erfolgs- und Reichweitenmessung können Cookies zum Einsatz kommen und Nutzerprofile erstellt werden. Nutzerprofile umfassen beispielsweise die besuchten Seiten oder betrachteten Inhalte auf unserer Website, Angaben zur Grösse von Bildschirm oder Browser-Fenster und den&nbsp;– zumindest ungefähren&nbsp;– Standort. <em>Grundsätzlich</em> werden Nutzerprofile ausschliesslich pseudonymisiert erstellt. Wir verwenden Nutzerprofile nicht für die Identifizierung einzelner Nutzerinnen und Nutzer. Einzelne Dienste von Dritten, bei denen Nutzerinnen oder Nutzer angemeldet sind, können die Nutzung unseres Online-Angebotes allenfalls dem Nutzerkonto oder Nutzerprofil beim jeweiligen Dienst zuordnen.</p>
    <p>Wir nutzen insbesondere:</p>
    <ul>
    <li><strong><a href="https://analytics.google.com/" rel="nofollow noopener noreferrer" target="_blank">Google Analytics:</a></strong> Erfolgs- und Reichweitenmessung; Anbieterin: Google; Google Analytics-spezifische Angaben: Messung auch über verschiedene Browser und Geräte hinweg <strong>(Cross-Device Tracking)</strong> sowie mit pseudonymisierten Internet Protocol (IP)-Adressen, die nur <em>ausnahmsweise</em> vollständig an Google in den USA übertragen werden, <a href="https://support.google.com/analytics/answer/6004245?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Datenschutz»</a>, <a href="https://tools.google.com/dlpage/gaoptout" rel="nofollow noopener noreferrer" target="_blank">«Browser Add-on zur Deaktivierung von Google Analytics»</a>.
    </li>
    <li><strong><a href="https://marketingplatform.google.com/about/tag-manager/" rel="nofollow noopener noreferrer" target="_blank">Google Tag Manager:</a></strong> Einbindung und Verwaltung von sonstigen Diensten für die Erfolgs- und Reichweitenmessung sowie weiteren Diensten von Google als auch von Dritten; Anbieterin: Google; Google Tag Manager-spezifische Angaben: <a href="https://support.google.com/tagmanager/answer/9323295?hl=de" rel="nofollow noopener noreferrer" target="_blank">«Mit Google Tag Manager erfasste Daten»</a>; weitere Angaben zum Datenschutz finden sich bei den einzelnen eingebundenen und verwalteten Diensten.
    </li>
    </ul>
    <h2>13. Schlussbestimmungen</h2>
    <p>Wir haben diese Datenschutzerklärung mit dem <a href="https://www.datenschutzpartner.ch/angebot-datenschutz-generator/" rel="nofollow noopener noreferrer" target="_blank">Datenschutz-Generator</a> von <a href="https://datenschutzpartner.ch/" rel="nofollow noopener noreferrer" target="_blank">Datenschutzpartner</a> erstellt.</p>
    <p>Wir können diese Datenschutzerklärung jederzeit anpassen und ergänzen. Wir werden über solche Anpassungen und Ergänzungen in geeigneter Form informieren, insbesondere durch Veröffentlichung der jeweils aktuellen Datenschutzerklärung auf unserer Website.</p>
  </x-slot>
</x-card-text>
